In [8]:
madedf.iloc[:, mnames]

,1306JP2009-03,1306JP2009-04,1306JP2009-11,1306JP2010-02,1306JP2010-10,1306JP2012-01,1306JP2012-05,1306JP2012-10,1306JP2012-11,1306JP2012-12,...,1306JP2015-09,1306JP2016-09,1306JP2016-10,1306JP2017-09,1306JP2018-08,1306JP2019-08,1306JP2020-04,1306JP2020-07,1306JP2020-10,1306JP2021-02
0,751.0,821.0,895.0,908.0,842.0,753.0,811.0,745.0,757.0,795.0,...,1504.0,1358.0,1362.0,1653.0,1811.0,1607.0,1415.0,1619.0,1671.0,1899.0
1,744.0,851.0,894.0,926.0,836.0,748.0,813.0,744.0,765.0,795.0,...,1489.0,1362.0,1372.0,1637.0,1793.0,1571.0,1397.0,1625.0,1699.0,1920.0
2,748.0,857.0,887.0,930.0,848.0,740.0,792.0,740.0,761.0,797.0,...,1501.0,1367.0,1381.0,1622.0,1784.0,1543.0,1396.0,1633.0,1708.0,1948.0
3,758.0,856.0,888.0,927.0,857.0,743.0,798.0,746.0,758.0,803.0,...,1471.0,1375.0,1387.0,1626.0,1772.0,1537.0,1448.0,1659.0,1710.0,1941.0
4,738.0,861.0,882.0,907.0,860.0,743.0,786.0,751.0,757.0,802.0,...,1473.0,1371.0,1383.0,1632.0,1786.0,1538.0,1475.0,1653.0,1719.0,1967.0
5,728.0,843.0,886.0,898.0,854.0,738.0,785.0,743.0,748.0,803.0,...,1441.0,1368.0,1389.0,1628.0,1786.0,1536.0,1499.0,1638.0,1708.0,2001.0
6,718.0,868.0,884.0,896.0,838.0,747.0,777.0,730.0,745.0,801.0,...,1531.0,1366.0,1376.0,1646.0,1782.0,1543.0,1486.0,1604.0,1705.0,2001.0
7,737.0,872.0,879.0,898.0,835.0,738.0,775.0,727.0,736.0,803.0,...,1503.0,1342.0,1374.0,1662.0,1760.0,1526.0,1503.0,1583.0,1710.0,2009.0
8,719.0,878.0,882.0,907.0,852.0,742.0,766.0,731.0,734.0,812.0,...,1506.0,1346.0,1379.0,1670.0,1723.0,1536.0,1473.0,1621.0,1704.0,2010.0
9,738.0,868.0,875.0,898.0,840.0,747.0,758.0,736.0,736.0,816.0,...,1489.0,1334.0,1386.0,1666.0,1751.0,1520.0,1503.0,1612.0,1693.0,2033.0
10,758.0,860.0,869.0,899.0,845.0,752.0,767.0,744.0,749.0,823.0,...,1488.0,1323.0,1389.0,1672.0,1737.0,1524.0,1508.0,1636.0,1678.0,2043.0
11,778.0,857.0,862.0,919.0,847.0,768.0,747.0,754.0,764.0,830.0,...,1499.0,1335.0,1392.0,1704.0,1727.0,1533.0,1494.0,1627.0,1700.0,2037.0
12,781.0,875.0,853.0,918.0,835.0,770.0,746.0,764.0,775.0,852.0,...,1519.0,1338.0,1404.0,1703.0,1738.0,1546.0,1513.0,1621.0,1688.0,2018.0
13,781.0,876.0,854.0,904.0,832.0,769.0,751.0,767.0,780.0,855.0,...,1490.0,1375.0,1398.0,1702.0,1731.0,1535.0,1505.0,1623.0,1699.0,2006.0
14,810.0,855.0,843.0,924.0,836.0,778.0,742.0,767.0,790.0,846.0,...,1454.0,1372.0,1402.0,1698.0,1724.0,1537.0,1487.0,1631.0,1680.0,2014.0
15,830.0,856.0,846.0,923.0,834.0,775.0,740.0,763.0,794.0,853.0,...,1479.0,1357.0,1410.0,1709.0,1740.0,1541.0,1474.0,1619.0,1687.0,1980.0
16,834.0,862.0,843.0,910.0,832.0,774.0,740.0,757.0,795.0,864.0,...,1479.0,1371.0,1415.0,1708.0,1739.0,1516.0,1495.0,1625.0,1680.0,2006.0
17,855.0,858.0,825.0,907.0,831.0,770.0,739.0,764.0,786.0,871.0,...,1411.0,1363.0,1417.0,1714.0,1750.0,1526.0,1492.0,1617.0,1679.0,1939.0
18,852.0,855.0,855.0,908.0,827.0,764.0,746.0,755.0,794.0,876.0,...,1446.0,1379.0,1425.0,1723.0,1771.0,1528.0,1517.0,1595.0,1673.0,NaN
19,812.0,839.0,NaN,NaN,821.0,NaN,743.0,753.0,794.0,NaN,...,NaN,1353.0,1429.0,1722.0,1773.0,1529.0,1522.0,1585.0,1675.0,NaN
20,797.0,866.0,NaN,NaN,NaN,NaN,735.0,747.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1780.0,1552.0,1533.0,1542.0,1641.0,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,755.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1780.0,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1775.0,NaN,NaN,NaN,NaN,NaN

In [9]:
madedf

,1306JP2009-03,1306JP2009-04,1306JP2009-05,1306JP2009-06,1306JP2009-07,1306JP2009-08,1306JP2009-09,1306JP2009-10,1306JP2009-11,1306JP2009-12,...,1306JP2021-09,1306JP2021-10,1306JP2021-11,1306JP2021-12,1306JP2022-01,1306JP2022-02,1306JP2022-03,1306JP2022-04,1306JP2022-05,1306JP2022-06
0,751.0,821.0,871.0,938.0,956.0,966.0,977.0,910.0,895.0,871.0,...,2042.0,2064.0,2126.0,2013.0,2122.0,1976.0,1977.5,2047.5,1998.0,2044.5
1,744.0,851.0,910.0,942.0,951.0,969.0,957.0,891.0,894.0,872.0,...,2043.0,2055.0,2113.0,2003.0,2125.0,2015.0,1938.5,2058.5,2017.5,2031.5
2,748.0,857.0,918.0,941.0,946.0,956.0,950.0,880.0,887.0,901.0,...,2081.0,2025.0,2136.0,2037.0,2082.0,2000.0,1958.5,2054.0,1978.0,2038.5
3,758.0,856.0,926.0,938.0,938.0,966.0,942.0,883.0,888.0,904.0,...,2106.0,2018.0,2121.0,2025.0,2078.0,2012.0,1920.5,2023.5,1964.0,2044.0
4,738.0,861.0,913.0,943.0,918.0,965.0,953.0,897.0,882.0,913.0,...,2127.0,2015.0,2119.0,2071.5,2072.0,2006.5,1869.0,1992.5,1950.5,2051.0
5,728.0,843.0,915.0,951.0,894.0,978.0,953.0,902.0,886.0,909.0,...,2147.0,2041.0,2102.0,2083.5,2102.5,2017.5,1835.0,1996.0,1930.0,2076.5
6,718.0,868.0,888.0,944.0,882.0,982.0,947.0,911.0,884.0,898.0,...,2129.0,2078.0,2087.0,2069.5,2088.0,2033.5,1832.0,1990.0,1967.5,2075.0
7,737.0,872.0,906.0,962.0,879.0,970.0,964.0,915.0,879.0,886.0,...,2157.0,2060.0,2095.0,2053.5,2060.5,2045.0,1904.5,1962.5,1967.0,2047.0
8,719.0,878.0,885.0,968.0,860.0,977.0,958.0,905.0,882.0,900.0,...,2162.0,2051.0,2124.0,2056.5,2069.5,2011.0,1878.5,1990.0,1969.5,2003.5
9,738.0,868.0,906.0,978.0,876.0,980.0,941.0,922.0,875.0,896.0,...,2184.0,2066.0,2131.0,2052.0,2061.0,1993.0,1887.0,2011.0,1989.0,1979.5
10,758.0,860.0,911.0,973.0,874.0,957.0,941.0,916.0,869.0,896.0,...,2163.0,2103.0,2134.0,2061.5,2000.0,2027.0,1905.5,1997.5,1962.5,1954.0
11,778.0,857.0,907.0,941.0,881.0,958.0,938.0,920.0,862.0,913.0,...,2157.0,2101.0,2120.0,2094.0,2019.0,2010.0,1930.5,1978.5,1979.5,1968.5
12,781.0,875.0,900.0,949.0,887.0,954.0,948.0,928.0,853.0,912.0,...,2164.0,2106.0,2115.0,2064.5,2005.0,2003.5,1981.0,1997.5,1999.0,1934.0
13,781.0,876.0,908.0,938.0,909.0,967.0,947.0,928.0,854.0,905.0,...,2129.0,2109.0,2126.0,2019.0,2008.0,1990.5,1989.5,2018.5,1982.5,1919.0
14,810.0,855.0,909.0,942.0,915.0,954.0,957.0,924.0,843.0,906.0,...,2111.0,2079.0,2126.0,2051.0,1973.5,1962.0,2011.5,2030.0,1978.5,1956.0
15,830.0,856.0,919.0,950.0,915.0,975.0,938.0,915.0,846.0,919.0,...,2159.0,2082.0,2098.0,2049.0,1968.0,1934.5,2059.5,2006.5,1980.0,1952.5
16,834.0,862.0,922.0,926.0,927.0,975.0,918.0,924.0,843.0,926.0,...,2156.0,2076.0,2107.0,2068.5,1917.0,1957.0,2066.0,1976.0,1990.5,1952.5
17,855.0,858.0,922.0,928.0,935.0,986.0,918.0,910.0,825.0,922.0,...,2145.0,2098.0,2066.0,2067.0,1956.0,1967.0,2065.0,1981.5,2025.5,1968.0
18,852.0,855.0,NaN,946.0,936.0,973.0,921.0,902.0,855.0,931.0,...,2121.0,2093.0,2028.5,2056.5,1973.5,NaN,2055.0,1962.0,2015.0,1991.5
19,812.0,839.0,NaN,953.0,937.0,977.0,NaN,896.0,NaN,929.0,...,2115.0,2079.0,2008.0,2084.0,NaN,NaN,2073.5,2000.0,NaN,2009.5
20,797.0,866.0,NaN,942.0,943.0,974.0,NaN,908.0,NaN,921.0,...,NaN,2082.0,NaN,2082.0,NaN,NaN,2073.0,NaN,NaN,1995.5
21,NaN,NaN,NaN,956.0,956.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2073.5,NaN,NaN,2049.0,NaN,NaN,1974.5
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
madedf2 = defmakedf.mdfmake("1320", 2009, 3)
madedf2.head()

end

,1320JP2009-03,1320JP2009-04,1320JP2009-05,1320JP2009-06,1320JP2009-07,1320JP2009-08,1320JP2009-09,1320JP2009-10,1320JP2009-11,1320JP2009-12,...,1320JP2021-09,1320JP2021-10,1320JP2021-11,1320JP2021-12,1320JP2022-01,1320JP2022-02,1320JP2022-03,1320JP2022-04,1320JP2022-05,1320JP2022-06
0,7390.0,8590.0,9260.0,9930.0,10160.0,10330.0,10480.0,10010.0,9870.0,9590.0,...,29120.0,29640.0,30500.0,28730.0,30170.0,27910.0,27655.0,28780.0,27860.0,28545.0
1,7330.0,8900.0,9590.0,9960.0,10140.0,10370.0,10290.0,9760.0,9870.0,9670.0,...,29180.0,29280.0,30400.0,28580.0,30240.0,28360.0,27195.0,28835.0,28050.0,28525.0
2,7400.0,8930.0,9680.0,9980.0,10090.0,10230.0,10180.0,9720.0,9740.0,9980.0,...,29780.0,28650.0,30700.0,28830.0,29370.0,28085.0,27420.0,28885.0,27360.0,28855.0
3,7550.0,9100.0,9680.0,9910.0,9940.0,10370.0,10160.0,9700.0,9820.0,10040.0,...,30300.0,28340.0,30500.0,28750.0,29360.0,28245.0,26805.0,28445.0,27230.0,29050.0
4,7280.0,9090.0,9560.0,10010.0,9640.0,10390.0,10310.0,9830.0,9820.0,10180.0,...,30600.0,28520.0,30350.0,29415.0,29095.0,28075.0,26015.0,27975.0,27265.0,29060.0

In [16]:
madedf = pd.concat([madedf, madedf2], axis=1)
madedf.head()

,1306JP2009-03,1306JP2009-04,1306JP2009-05,1306JP2009-06,1306JP2009-07,1306JP2009-08,1306JP2009-09,1306JP2009-10,1306JP2009-11,1306JP2009-12,...,1320JP2021-09,1320JP2021-10,1320JP2021-11,1320JP2021-12,1320JP2022-01,1320JP2022-02,1320JP2022-03,1320JP2022-04,1320JP2022-05,1320JP2022-06
0,751.0,821.0,871.0,938.0,956.0,966.0,977.0,910.0,895.0,871.0,...,29120.0,29640.0,30500.0,28730.0,30170.0,27910.0,27655.0,28780.0,27860.0,28545.0
1,744.0,851.0,910.0,942.0,951.0,969.0,957.0,891.0,894.0,872.0,...,29180.0,29280.0,30400.0,28580.0,30240.0,28360.0,27195.0,28835.0,28050.0,28525.0
2,748.0,857.0,918.0,941.0,946.0,956.0,950.0,880.0,887.0,901.0,...,29780.0,28650.0,30700.0,28830.0,29370.0,28085.0,27420.0,28885.0,27360.0,28855.0
3,758.0,856.0,926.0,938.0,938.0,966.0,942.0,883.0,888.0,904.0,...,30300.0,28340.0,30500.0,28750.0,29360.0,28245.0,26805.0,28445.0,27230.0,29050.0
4,738.0,861.0,913.0,943.0,918.0,965.0,953.0,897.0,882.0,913.0,...,30600.0,28520.0,30350.0,29415.0,29095.0,28075.0,26015.0,27975.0,27265.0,29060.0

In [1]:
import defmakedf
new1306 = defmakedf.presentstock("1306")

return 1306 df end

In [2]:
new1306

19    2044.5
20    2031.5
21    2038.5
22    2044.0
23    2051.0
24    2076.5
25    2075.0
26    2047.0
27    2003.5
28    1979.5
29    1954.0
30    1968.5
31    1934.0
32    1919.0
33    1956.0
34    1952.5
35    1952.5
36    1968.0
37    1991.5
38    2009.5
39    1995.5
40    1974.5
Name: Close, dtype: float64

In [5]:
import numpy as np
import pandas as pd
import pandas_datareader as data 
import datetime as datetime

x="1306"
stcode = x+".JP"
dt_now = datetime.datetime.now()
ly = dt_now.year
lm = dt_now.month
ld = dt_now.day

stock = data.DataReader(stcode,'stooq',start=datetime.date(ly, lm-2, 1),end=datetime.date(ly,lm,ld))
#datetime.datetime(ly,lm,ld))

stock = stock.sort_values(by='Date')

#%Y-%m の形にそろえる列ｙｍを作成し、リスト化
stock['ym'] = stock.index.strftime("%Y-%m")

listym = list(stock['ym'])

#ym の重複をなくす
mlist = stock['ym'].unique()
latm = mlist[-2]


#DateのMultiindexを解除
stock = stock.reset_index()

sclist = []
mnths = []

#毎月の株価を格納するリストを作成
sc = stock['Close'][stock['ym']==mlist[-2]]
listedsc = list(sc)
mn = str(x)+"JP"+str(mlist[-2])
listedmn = list(mn)
mn

'1306JP2022-06'

In [8]:
listedsc

[2044.5,
 2031.5,
 2038.5,
 2044.0,
 2051.0,
 2076.5,
 2075.0,
 2047.0,
 2003.5,
 1979.5,
 1954.0,
 1968.5,
 1934.0,
 1919.0,
 1956.0,
 1952.5,
 1952.5,
 1968.0,
 1991.5,
 2009.5,
 1995.5,
 1974.5]

In [15]:
scdf = pd.DataFrame(listedsc, columns=[mn])
scdf

    1306JP2022-06
0          2044.5
1          2031.5
2          2038.5
3          2044.0
4          2051.0
5          2076.5
6          2075.0
7          2047.0
8          2003.5
9          1979.5
10         1954.0
11         1968.5
12         1934.0
13         1919.0
14         1956.0
15         1952.5
16         1952.5
17         1968.0
18         1991.5
19         2009.5
20         1995.5
21         1974.5

In [16]:

import numpy as np
import pandas as pd
import pandas_datareader.data as web
import datetime as datetime

dt_now = datetime.datetime.now()
ly = dt_now.year
lm = dt_now.month
ld = dt_now.day

#codejp = input(int())
#codejp = "1306"
#stockcode = codejp+".JP"
import defmakedf


codes = ["3064", "2124", "2379", ]
returndf2 = pd.DataFrame()
madedf2 = pd.DataFrame()

for c in codes:
    madedf = defmakedf.mdfmake(c, 2009, 3)
    returndf = defmakedf.mdfreturn(c, 2009, 3)
    madedf2 = pd.concat([madedf2, madedf], axis=1)
    returndf2 = pd.concat([returndf2, returndf], axis=1)
    #
retrdf = defmakedf.rdf(returndf2)
plus5list = defmakedf.plusper(madedf2, retrdf, 5)

make3064df end
return 3064 df end
make2124df end
return 2124 df end
make2379df end
return 2379 df end

In [27]:
len(madedf2.columns)

480

In [29]:
retrdf["growth"] = retrdf

             mname  mnum       nxrt
0    3064JP2009-03     0  -5.419195
1    3064JP2009-04     1  12.778831
2    3064JP2009-05     2  16.023528
3    3064JP2009-06     3  11.108635
4    3064JP2009-07     4  30.610710
..             ...   ...        ...
477  2379JP2022-02   477  -0.884956
478  2379JP2022-03   478  26.785714
479  2379JP2022-04   479 -11.619718
480  2379JP2022-05   480  -0.265604
481  2379JP2022-06   481  -3.195739

[482 rows x 3 columns]

In [28]:
madedf2

,3064JP2009-03,3064JP2009-04,3064JP2009-05,3064JP2009-06,3064JP2009-07,3064JP2009-08,3064JP2009-09,3064JP2009-10,3064JP2009-11,3064JP2009-12,...,2379JP2021-09,2379JP2021-10,2379JP2021-11,2379JP2021-12,2379JP2022-01,2379JP2022-02,2379JP2022-03,2379JP2022-04,2379JP2022-05,2379JP2022-06
0,11.482,14.202,13.748,15.471,18.130,20.608,25.927,22.723,20.398,17.284,...,3543.91,4059.39,4089.13,3910.70,3970.17,3335.74,3440.0,3405.0,4310.0,3860.0
1,12.449,14.051,13.962,15.833,18.009,20.216,25.593,21.938,21.454,17.676,...,3598.43,4104.00,4074.26,3831.39,3737.22,3534.00,3340.0,3390.0,4255.0,3780.0
2,12.087,14.324,13.962,15.532,17.526,19.641,25.621,21.273,21.998,17.676,...,3717.39,4084.17,4128.78,4004.87,3613.30,3350.61,3345.0,3385.0,4180.0,3835.0
3,12.449,14.202,14.353,15.411,17.828,22.210,25.235,21.153,21.636,16.952,...,3806.61,4014.78,4108.96,3925.57,3677.74,3444.78,3105.0,3320.0,3940.0,3780.0
4,12.631,14.020,16.015,15.381,17.406,21.697,24.926,21.998,20.910,17.043,...,3885.91,4079.22,4128.78,4099.04,3662.87,3306.00,2967.0,3195.0,3860.0,3740.0
5,12.299,14.353,15.471,15.230,16.469,23.117,25.476,21.546,20.790,16.742,...,3900.78,4237.83,4198.17,4138.70,3702.52,3365.48,3055.0,3275.0,3725.0,3755.0
6,11.967,14.444,15.833,15.351,16.681,26.952,25.536,22.603,20.790,16.559,...,3890.87,4237.83,4188.26,4153.57,3548.87,3504.26,2993.0,3300.0,3790.0,3790.0
7,12.087,14.353,16.317,15.683,15.893,26.410,25.621,22.361,20.699,16.136,...,4064.35,4163.48,4381.57,4034.61,3444.78,3662.87,3180.0,3355.0,3835.0,3710.0
8,12.329,14.110,15.833,15.411,14.807,26.590,24.926,22.783,19.944,16.742,...,4039.57,4133.74,4411.30,4079.22,3211.83,3519.13,3135.0,3490.0,3765.0,3610.0
9,12.117,14.142,15.593,15.561,15.863,26.410,24.145,21.998,18.432,16.257,...,4247.74,4242.78,4579.83,3920.61,3325.83,3360.52,3175.0,3560.0,3975.0,3525.0
10,12.267,13.991,15.593,16.377,15.713,25.743,22.875,21.303,18.432,16.469,...,4242.78,4168.43,4629.39,3955.30,3276.26,3434.87,3140.0,3915.0,3830.0,3440.0
11,12.419,14.202,15.653,16.317,16.710,25.204,22.512,22.300,18.585,16.439,...,4153.57,3950.35,4778.09,3999.91,3350.61,3454.70,3150.0,4050.0,4035.0,3430.0
12,12.329,14.081,15.775,16.257,17.767,25.621,22.300,22.665,18.585,16.771,...,4143.65,4123.83,4753.30,3836.35,3529.04,3529.04,3260.0,4190.0,4155.0,3330.0
13,13.991,14.353,15.471,15.593,18.130,24.716,21.303,22.481,18.734,16.077,...,4049.48,4178.35,4624.43,3672.78,3568.70,3429.91,3260.0,4055.0,3975.0,3400.0
14,14.264,13.962,NaN,16.469,18.130,25.235,21.998,22.481,17.164,16.257,...,4089.13,4084.17,4550.09,3796.70,3439.83,3380.35,3150.0,4040.0,3755.0,3495.0
15,13.902,13.902,NaN,19.279,18.703,24.716,23.993,22.814,16.226,16.377,...,4198.17,4069.30,4322.09,3895.83,3474.52,3306.00,3260.0,3915.0,3795.0,3475.0
16,13.902,13.870,NaN,18.887,18.855,24.838,23.389,23.811,15.713,16.921,...,4361.74,4034.61,4227.91,3985.04,3375.39,3415.00,3270.0,4055.0,3750.0,3605.0
17,13.748,13.598,NaN,17.588,19.340,25.836,23.631,23.721,14.988,16.862,...,4158.52,4148.61,4069.30,3905.74,3479.48,3390.00,3290.0,4100.0,3795.0,3760.0
18,14.233,13.478,NaN,17.224,20.155,26.410,23.207,23.237,16.499,16.317,...,4019.74,4044.52,3955.30,3816.52,3553.83,NaN,3290.0,4200.0,3765.0,3750.0
19,14.474,13.539,NaN,17.828,19.340,26.202,NaN,22.210,NaN,15.893,...,4222.96,4014.78,3945.39,3895.83,NaN,NaN,3325.0,4260.0,NaN,3725.0
20,14.504,13.718,NaN,18.009,19.340,26.049,NaN,21.273,NaN,16.046,...,NaN,4054.43,NaN,3895.83,NaN,NaN,3390.0,NaN,NaN,3760.0
21,NaN,NaN,NaN,17.950,19.944,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3880.96,NaN,NaN,3360.0,NaN,NaN,3755.0
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN